In [14]:
import pandas as pd
data_stat = pd.read_csv (r'https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv')
data_stat.sample(10)

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,...,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
82000,1,-122.314699,47.582985,89738,101983,101983,3334050,Matched,Intersection,31265.0,...,Unknown,Unknown,NaN,9272047.0,NaN,27,From opposite direction - both going straight ...,0,0,N
111268,1,-122.312563,47.661266,122941,139258,139258,3563843,Matched,Block,NaN,...,Unknown,Unknown,NaN,12212018.0,NaN,32,One parked--one moving,0,0,N
28734,1,-122.355409,47.700951,33532,46841,46841,2022902,Matched,Block,NaN,...,Dry,Daylight,NaN,5053022.0,NaN,11,From same direction - both going straight - bo...,0,0,N
155030,2,-122.360973,47.571459,172808,220777,221057,3787303,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,14,From same direction - both going straight - on...,0,0,N
125521,2,-122.254716,47.517163,139592,158490,158510,3672110,Matched,Block,NaN,...,Wet,Dark - Street Lights On,NaN,NaN,NaN,13,From same direction - both going straight - bo...,0,0,N
71532,1,-122.366182,47.667183,78016,94041,94041,3210756,Matched,Intersection,25431.0,...,Dry,Dark - Street Lights On,NaN,9069009.0,NaN,10,Entering at angle,0,0,N
130120,1,-122.334176,47.572440,144807,167363,167383,E320008,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,13,From same direction - both going straight - bo...,0,0,N
98986,2,-122.300711,47.665333,108786,122122,122122,3466715,Matched,Block,NaN,...,Dry,Daylight,NaN,11257013.0,NaN,13,From same direction - both going straight - bo...,0,0,N
68838,1,-122.325041,47.633859,75237,86688,86688,3285800,Matched,Block,NaN,...,Dry,Unknown,NaN,8341034.0,NaN,32,One parked--one moving,0,0,N
93028,1,-122.314910,47.526905,102018,116284,116284,3331633,Matched,Block,NaN,...,Dry,Dark - Street Lights On,NaN,10364013.0,NaN,32,One parked--one moving,0,0,N

In [15]:
data_stat.describe()

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,INTKEY,SEVERITYCODE.1,PERSONCOUNT,PEDCOUNT,PEDCYLCOUNT,VEHCOUNT,SDOT_COLCODE,SDOTCOLNUM,SEGLANEKEY,CROSSWALKKEY
count,194673.000000,189339.000000,189339.000000,194673.000000,194673.000000,194673.000000,65070.000000,194673.000000,194673.000000,194673.000000,194673.000000,194673.000000,194673.000000,1.149360e+05,194673.000000,1.946730e+05
mean,1.298901,-122.330518,47.619543,108479.364930,141091.456350,141298.811381,37558.450576,1.298901,2.444427,0.037139,0.028391,1.920780,13.867768,7.972521e+06,269.401114,9.782452e+03
std,0.457778,0.029976,0.056157,62649.722558,86634.402737,86986.542110,51745.990273,0.457778,1.345929,0.198150,0.167413,0.631047,6.868755,2.553533e+06,3315.776055,7.226926e+04
min,1.000000,-122.419091,47.495573,1.000000,1001.000000,1001.000000,23807.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.007024e+06,0.000000,0.000000e+00
25%,1.000000,-122.348673,47.575956,54267.000000,70383.000000,70383.000000,28667.000000,1.000000,2.000000,0.000000,0.000000,2.000000,11.000000,6.040015e+06,0.000000,0.000000e+00
50%,1.000000,-122.330224,47.615369,106912.000000,123363.000000,123363.000000,29973.000000,1.000000,2.000000,0.000000,0.000000,2.000000,13.000000,8.023022e+06,0.000000,0.000000e+00
75%,2.000000,-122.311937,47.663664,162272.000000,203319.000000,203459.000000,33973.000000,2.000000,3.000000,0.000000,0.000000,2.000000,14.000000,1.015501e+07,0.000000,0.000000e+00
max,2.000000,-122.238949,47.734142,219547.000000,331454.000000,332954.000000,757580.000000,2.000000,81.000000,6.000000,2.000000,12.000000,69.000000,1.307202e+07,525241.000000,5.239700e+06